# https://www.mkdocs.org/user-guide/configuration/
# https://www.mkdocs.org/user-guide/writing-your-docs/
# https://www.mkdocs.org/user-guide/writing-your-docs/#writing-with-markdown
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/writing-your-docs/
# https://mkdocs.readthedocs.io/en/0.15.2/user-guide/styling-your-docs/
# https://example-mkdocs-basic.readthedocs.io/en/latest/
# https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml
# mkdocs.yml

site_name: TheCleaners
site_url: https://day3bits.com/TheCleaners
repo_url: https://github.com/SamErde/TheCleaners
repo_name: TheCleaners
# edit_uri: edit/main/docs/
# edit_uri_template:
site_description: Clean up all of the loose ends in your system with TheCleaners. We take care of temp files, IIS logs, Exchange Server logs, and more! # meta tag to the generated HTML header
site_author: Sam Erde # meta tag to the generated HTML header
copyright: 2024
# remote_branch:
# remote_name:
docs_dir: docs
# site_dir:
# extra_css:
# extra_javascript:
# extra_templates:
# extra:
theme: readthedocs
# theme:
#     name: readthedocs
#     locale: en
    # custom_dir: my_theme_customizations/
    # static_templates:
    #     - sitemap.html
    # include_sidebar: true
nav:
  - Home: index.md
    - Functions:
      - Function1: 'Start-Cleaning.md'
      - Function2: 'Clear-OldExchangeLogs.md'
      - Function3: 'Clear-OldIISLogs.md'
